apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata: 
  name: tls-svc-csr 
spec: 
  request: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQmV6Q0NBU0lDQVFBd1VERVZN
    Qk1HQTFVRUNoTU1jM2x6ZEdWdE9tNXZaR1Z6TVRjd05RWURWUVFERXk1egplWE4wWlcwNmJtOWta
    VHAwYkhNdGNHOWtMblJzY3kxMFpYTjBMbkJ2WkM1amJIVnpkR1Z5TG14dlkyRnNNRmt3CkV3WUhL
    b1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFOWZ5aitYeDF4Zkx5SEQycHYvSmxyNjR1dUE1TWpP
    Qk4KMElTZTF1UUhvVW1GZGZuWUc2VnlPYnNCVzFzQURIUFJVMW91QmhLa2dPUTVWUDI0dTFlV09x
    QndNRzRHQ1NxRwpTSWIzRFFFSkRqRmhNRjh3WFFZRFZSMFJCRll3VklJaWRHeHpMWE4yWXk1MGJI
    TXRkR1Z6ZEM1emRtTXVZMngxCmMzUmxjaTVzYjJOaGJJSWlkR3h6TFhCdlpDNTBiSE10ZEdWemRD
    NXdiMlF1WTJ4MWMzUmxjaTVzYjJOaGJJY0UKd0FBQ0dJY0VDZ0FpQWpBS0JnZ3Foa2pPUFFRREFn
    TkhBREJFQWlCRktkUSt5OFNDWW1CSG1SU0ZpYllLSnhXRQpvREdvU2hMcytybm9RSjAvNlFJZ05Z
    N2xTK09wanA0VGQ0UW90c1Z1YkJXYnBUY2VxbkI4UjkzN041Q0V0WHc9Ci0tLS0tRU5EIENFUlRJ
    RklDQVRFIFJFUVVFU1QtLS0tLQo=
  signerName: kubernetes.io/kubelet-serving 
  usages: 
  - digital signature 
  - key encipherment 
  - server auth 
